---
- name: configuracion de servidor nfs
  hosts: centos
  become: yes
 

  tasks:
    - name: Instalar servidor NFS
      ansible.builtin.dnf:
        name: nfs-utils
        state: present
   
    - name: Asegurar que el servicio NFS este iniciado y habilitado
      ansible.builtin.service:
        name: nfs-utils
        state: started
        enabled: yes

    - name: permitir conexiones al puerto 2049/tcp en el firewall
      ansible.posix.firewalld:
        port: 2049/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Crear directorio compartido
      ansible.builtin.file:
        path: var/nfs_shared
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'

    - name: Configurar /etc/exports para compartir
      ansible.builtin.copy:
        dest: /etc/exports
        content: var/nfs_shared
        owner: root
        group: root
        mode: '0644'
      notify: Recargar configuracion de NFS

  handlers:
     - name: Recargar configuracion de NFS
       ansible.builtin.command: 
         cmd: exportfs -r

